# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartstay_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Tanishq2002

# Driver & Hibernate Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open-In-View warning
spring.jpa.open-in-view=false

# Default Security Username & Password (Testing ke liye)
spring.security.user.name=admin
spring.security.user.password=admin123

# Server Configuration
server.port=8080

# Application Name
spring.application.name=smartstay-backend